apiVersion: v1
kind: ConfigMap
metadata:
  name: avsec-config
data:
  NODE_ENV: development
  PORT: "3005"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  ENABLE_BULLMQ_EVENTS: "true"
  OUTBOX_BATCH_SIZE: "10"
  MAX_RETRY_COUNT: "5"
  BETTER_AUTH_ENABLED: "true"
  BETTER_AUTH_URL: https://api.k3s.faan-avsec.naakwu.app
  ALLOWED_ORIGINS: https://k3s.faan-avsec.naakwu.app,https://admin.k3s.faan-avsec.naakwu.app
  TEMPORAL_ADDRESS: temporal-frontend:7233
  TEMPORAL_NAMESPACE: faan-avsec-odc
  TEMPORAL_ODC_TASK_QUEUE: odc-workflow
  TEMPORAL_WORKER_AUTO_START: "true"
  MAILPIT_ENABLED: "true"
  MAILPIT_SMTP_HOST: mailpit
  MAILPIT_SMTP_PORT: "1025"
  MAILPIT_SENDER_EMAIL: noreply@faan-avsec.local
  AWS_ENDPOINT_URL: http://ministack:4566
  AWS_S3_BUCKET_NAME: my-bucket
  AWS_REGION: us-east-1
  SENTRY_PROFILING_ENABLED: "false"
