apiVersion: batch/v1
kind: Job
metadata:
  name: flowkit-migration
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: flowkit-demo
      imagePullSecrets:
        - name: flowkit-demo-registry
      containers:
        - name: flowkit-migration
          image: docker.pigstycoders.com/flowkit-demo-dev/flowkit-demo
          imagePullPolicy: Always
          command: ["bun", "run", "db:migrate"]
          envFrom:
            - configMapRef:
                name: flowkit-demo-config
            - secretRef:
                name: flowkit-demo-runtime