apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ops-ingress-auth
spec:
  basicAuth:
    secret: ops-ingress-auth
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faan-avsec
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - secretName: faan-avsec-k3s-tls
      hosts:
        - k3s.faan-avsec.naakwu.app
        - admin.k3s.faan-avsec.naakwu.app
        - api.k3s.faan-avsec.naakwu.app
        - temporal.k3s.faan-avsec.naakwu.app
        - mail.k3s.faan-avsec.naakwu.app
  rules:
    - host: k3s.faan-avsec.naakwu.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: public-web
                port:
                  name: http
    - host: admin.k3s.faan-avsec.naakwu.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: internal-web
                port:
                  name: http
    - host: api.k3s.faan-avsec.naakwu.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: faan-avsec-ops
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: faan-avsec-dev-ops-ingress-auth@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: faan-avsec-k3s-tls
      hosts:
        - temporal.k3s.faan-avsec.naakwu.app
        - mail.k3s.faan-avsec.naakwu.app
  rules:
    - host: temporal.k3s.faan-avsec.naakwu.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-web
                port:
                  name: http
    - host: mail.k3s.faan-avsec.naakwu.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mailpit
                port:
                  name: http
