apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - temporal-namespace-job.yaml
  - configmap.yaml
  - postgres.yaml
  - mailpit.yaml
  - flowkit-api.yaml
  - flowkit-worker.yaml
  - flowkit-notify.yaml
  - flowkit-migration.yaml
  - flowkit-seed.yaml
  - ingress.yaml
